baseURL = "http://example.com/"
title = "EchoSlate"
languageCode = "en-us"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false  
enableMissingTranslationPlaceholders = true

[outputs]
  home = ["HTML", "SearchIndex"]
  section = ["HTML"]
  page = ["HTML"]
  list = ["HTML"]

[outputFormats]
  [outputFormats.SearchIndex]
    name = "SearchIndex"
    mediaType = "application/json"
    baseName = "index"
    isPlainText = true

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    title = "EchoSlate"
    contentDir = "content/en"
    [languages.en.params]
      description = "A digital portfolio website to showcase resumes and projects."
    [languages.en.outputs]
      home = ["HTML", "SearchIndex"]
      section = ["HTML"]
      page = ["HTML"]
      list = ["HTML"]

    [[languages.en.menu.main]]
      identifier = "users"
      name = "Users"
      url = "/users/"
      weight = 2

    [[languages.en.menu.main]]
      identifier = "upload"
      name = "Upload"
      url = "/upload/"
      weight = 3

    [[languages.en.menu.main]]
      identifier = "search"
      name = "Search"
      url = "/search/"
      weight = 4

    [[languages.en.menu.main]]
      identifier = "about"
      name = "About"
      url = "/about/"
      weight = 5

    [[languages.en.menu.main]]
      identifier = "contact"
      name = "Contact"
      url = "/contact/"
      weight = 6

  [languages.es]
    languageName = "Español"
    weight = 2
    title = "EchoSlate"
    contentDir = "content/es"
    [languages.es.params]
      description = "Un sitio web de portafolio digital para mostrar currículums y proyectos."
    [languages.es.outputs]
      home = ["HTML", "SearchIndex"]
      section = ["HTML"]
      page = ["HTML"]
      list = ["HTML"]

    [[languages.es.menu.main]]
      identifier = "users"
      name = "Usuarios"
      url = "/es/users/"
      weight = 2

    [[languages.es.menu.main]]
      identifier = "upload"
      name = "Subir"
      url = "/es/upload/"
      weight = 3

    [[languages.es.menu.main]]
      identifier = "search"
      name = "Buscar"
      url = "/es/search/"
      weight = 4

    [[languages.es.menu.main]]
      identifier = "about"
      name = "Acerca de"
      url = "/es/about/"
      weight = 5

    [[languages.es.menu.main]]
      identifier = "contact"
      name = "Contacto"
      url = "/es/contact/"
      weight = 6

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    noClasses = false  # Set to true to disable CSS classes for code highlighting
